---
pipeline:
  build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t dp-limesurvey .
    when:
      branch: master
      event: push
  publish:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+dp_non_iapi" -p=$${DOCKER_PASSWORD} quay.io
      - docker push quay.io/ukhomeofficedigital/dp-limesurvey:latest
    when:
      branch: master
      event: push
