---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dp-limesurvey-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: dp-limesurvey-service
          servicePort: 10080
        path: /
