---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: limesurvey-config
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2-encrypted-eu-west-2a
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
